# bashrc: executed by bash for non-login shells.

# shellcheck disable=SC2148

# If not running interactively, don't do anything
[[ ! "$-" == *i* ]] && return

case "$TERM" in
    xterm-color|*-256color) export COLOR_TERM=yes;;
esac

# Set XDG environment variables
if [[ "$OSTYPE" = linux* ]]; then
  export XDG_CONFIG_HOME="${XDG_CONFIG_HOME-$HOME/.config}"
  export XDG_DATA_HOME="${XDG_DATA_HOME-$HOME/.local/share}"
  export XDG_CACHE_HOME="${XDG_CACHE_HOME-$HOME/.cache}"
elif [[ "$OSTYPE" = darwin* ]]; then
  # There doesn't seem to be a consensus for supporting the DATA path for macOS
  export XDG_CONFIG_HOME="${XDG_CONFIG_HOME-$HOME/Library/Application Support}"
  export XDG_DATA_HOME="${XDG_DATA_HOME-$HOME/Library/Application Support}"
  export XDG_CACHE_HOME="${XDG_CACHE_HOME-$HOME/Library/Caches}"
  export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR-/run/user/$UID}"
else
  # currrently unsupported
  return
fi

# Load bash configuration
for f in "${XDG_CONFIG_HOME}"/bash/*.sh; do
  # shellcheck disable=SC1090
  [ -f "$f" ] && . "$f"
done
