# bashrc: executed by bash for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Set XDG dirs
if [ "$OSTYPE" = darwin* ]; then
  # There doesn't seem to be a consensus for supporting the DATA path for macOS
  XDG_CONFIG_HOME="$HOME/Library/Application Support"
  XDG_DATA_HOME="$HOME/Library/Application Support"
  XDG_CACHE_HOME="$HOME"/Library/Caches
  XDG_RUNTIME_DIR="$TMPDIR"/
else
  XDG_CONFIG_HOME="$HOME"/.config
  XDG_DATA_HOME="$HOME"/.local/share
  XDG_CACHE_HOME="$HOME"/.cache
fi

# Load bash files
for F in "${XDG_CONFIG_HOME}"/bash/*.sh; do
  [ -f "$F" ] && . "$F"
done
